[versions]
agp = "8.7.3"
kotlin = "2.0.21"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
hilt = "2.51.1"
room = "2.6.1"
coroutines = "1.7.3"
retrofit = "2.10.0"
navigation = "2.8.5"
navigation-plugin = "2.0.21"
kotlin-serialization = "1.7.3"
ksp = "2.0.21-1.0.27"
compose-bom = "2024.12.01"
compose-activity = "1.9.3"
compose-viewmodels = "2.8.7"
coil = "3.0.4"
ktor-version = "3.0.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
hilt = { group = "com.google.dagger", name="hilt-android", version.ref="hilt" }
hilt-compiler = { group = "com.google.dagger", name="hilt-compiler", version.ref="hilt" }
room-runtime = { group = "androidx.room", name="room-runtime", version.ref="room" }
room-compiler = { group = "androidx.room", name="room-compiler", version.ref="room" }
room-ktx = { group = "androidx.room", name="room-ktx", version.ref="room" }
room-testing = { group = "androidx.room", name="room-testing", version.ref="room" }
room-paging = { group = "androidx.room", name="room-paging", version.ref="room" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref="coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref="coroutines" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref="retrofit" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref="navigation" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref="navigation" }
navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref="navigation" }
kotlin-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref="kotlin-serialization" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref="compose-bom" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref="compose-activity" }
compose-viewmodels = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref="compose-viewmodels" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref="coil" }
coil-network = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref="coil" }
ktor-core = { group = "io.ktor", name = "ktor-client-core", version.ref="ktor-version" }
ktor-client-android = { group = "io.ktor", name = "ktor-client-android", version.ref="ktor-version" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref="ktor-version" }
ktor-serialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref="ktor-version" }
ktor-client-contentnegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref="ktor-version" }
ktor-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref="ktor-version" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
navigation = { id = "plugin.serialization", version.ref = "navigation-plugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kapt = { id = "kotlin-kapt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
